name: Destroy RDS Infra 

on:
  workflow_dispatch:

jobs:
  destroy-rds:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      #AWS CREDENTIALS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION}}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: myGitHubActions
      #Terraform execution
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_subnet_a_id: ${{ vars.SUBNET_A }}
          TF_VAR_subnet_b_id: ${{ vars.SUBNET_B }}
          TF_VAR_security_group_db: ${{ vars.SG_DB_FASTFOOD }}